modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="LGPL-2.1"

[[mods]] #mandatory
modId="magnesium_extras" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Magnesium/Rubidium Extras" #mandatory
credits="TeamDeusVult, TexTrue, LocalizedMC" #optional
authors="Team Potato" #optional
description='''
Adds Extra Settings to Magnesium/Rubidium.
'''
